version: '3'
services:
  mongodb:
    restart: always
    build: .
    ports:
      - 4000:4000
    volumes:
      - ./:/code
  mongo:
    image: mongo
    command: mongod --quiet --logpath /dev/null
    ports:
      - 27018:27017
    volumes:
      - mongodb:/data/db
volumes:
 mongodb: